name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: sbt to Maven Central
#      uses: cosmincatalin/sbt-to-maven-central@v1.0.4
      env:
        NEXUS_USER: "test_u"
#        NEXUS_USER: ${{ secrets.NEXUS_USER }}
        NEXUS_PASSWORD: "test_pw"
#        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        GPG_PK: "test_pk"
#        GPG_PK: ${{ secrets.GPG_PK }}
        GPG_PASSPHRASE: "test_p"
#        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
        mkdir -p ~/.sbt/1.0/plugins/

        touch ~/.sbt/1.0/sonatype.sbt
        cat /dev/null > ~/.sbt/1.0/sonatype.sbt
        {
          echo 'credentials += Credentials("Sonatype Nexus Repository Manager",';
          echo '        "oss.sonatype.org",';
          echo '        "'"$NEXUS_USER"'",'
          echo '        "'"$NEXUS_PASSWORD"'")'
        } >> ~/.sbt/1.0/sonatype.sbt
        sha1sum ~/.sbt/1.0/sonatype.sbt

        touch ~/.private.key
        cat /dev/null > ~/.private.key
        echo -e "$GPG_PK" > ~/.private.key
        gpg --import --batch ~/.private.key
        rm -rf ~/.private.key

        touch ~/.sbt/1.0/plugins/plugins.sbt
        cat /dev/null > ~/.sbt/1.0/plugins/plugins.sbt
        {
          echo 'addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.5")'
        } >> ~/.sbt/1.0/plugins/plugins.sbt

        sbt --debug +publish
