name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: sbt to Maven Central
      uses: cosmincatalin/sbt-to-maven-central@v1.0.0
      env:
        NEXUS_USER: ${{ secrets.NEXUS_USER }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        GPG_PK: ${{ secrets.GPG_PK }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
