name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: sbt to Maven Central
      uses: cosmincatalin/sbt-to-maven-central@v1.0.0-2
      env:
        NEXUS_USER: ${{ secrets.NEXUS_USER }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        NEXUS_PK: ${{ secrets.NEXUS_PK }}
        NEXUS_PASSPHRASE: ${{ secrets.NEXUS_PASSPHRASE }}
